### ISSUE TITLE
bcrypt hashes

### ISSUE THREAD

**Issue by the-rene** [flocke/user_external_pgsql#1]
If possible, please add support for bcrypt for the password hashes, we'd need that for our database.

**Comment by flocke** [comment]
I haven't touched this in a while, but I will look into it.

**Comment by flocke** [comment]
Which PHP version are you guys using? It might be as easy as replacing the `crypt()` function with `password_verify()`.

**Comment by flocke** [comment]
@the-rene I updated it to use the `password_verify()` function in PHP. This should make it work with bcrypt hashes.
